const ITEMS = [
  {
    id: 1,
    title: "Caminhada do Forró (Concentração: Academia High Five Fitness)",
    location: "Caminhada do Forró",
    capacity: "",
    date: "21/06/2026",
    dateFilter: "21 Jun",
    type: "shows",
    lat: -8.4231,
    lng: -37.0583,
  },
  {
    id: 2,
    title: "Spice Bone",
    location: "Polo Multimusical Rubens Pastor",
    capacity: "",
    date: "19/06/2026",
    dateFilter: "19 Jun",
    type: "shows",
    lat: -8.4147,
    lng: -37.0521,
  },
  {
    id: 3,
    title: "Laranjão",
    location: "Polo Multimusical Rubens Pastor",
    capacity: "",
    date: "19/06/2026",
    dateFilter: "19 Jun",
    type: "shows",
    lat: -8.4195,
    lng: -37.0489,
  },
  {
    id: 4,
    title: "Dkaws",
    location: "Polo Multimusical Rubens Pastor",
    capacity: "",
    date: "19/06/2026",
    dateFilter: "19 Jun",
    type: "shows",
    lat: -8.4218,
    lng: -37.0624,
  },
  {
    id: 5,
    title: "Verdant",
    location: "Polo Multimusical Rubens Pastor",
    capacity: "",
    date: "19/06/2026",
    dateFilter: "19 Jun",
    type: "shows",
    lat: -8.4132,
    lng: -37.0567,
  },
  {
    id: 6,
    title: "Bruno C'zar",
    location: "Polo Multimusical Rubens Pastor",
    capacity: "",
    date: "20/06/2026",
    dateFilter: "20 Jun",
    type: "shows",
    lat: -8.4174,
    lng: -37.0475,
  },
  {
    id: 7,
    title: "Cobaias do Sisal",
    location: "Polo Multimusical Rubens Pastor",
    capacity: "",
    date: "20/06/2026",
    dateFilter: "20 Jun",
    type: "shows",
    lat: -8.4245,
    lng: -37.0512,
  },
  {
    id: 8,
    title: "Armaggedon",
    location: "Polo Multimusical Rubens Pastor",
    capacity: "",
    date: "20/06/2026",
    dateFilter: "20 Jun",
    type: "shows",
    lat: -8.4159,
    lng: -37.0601,
  },
  {
    id: 9,
    title: "777 Gang",
    location: "Polo Multimusical Rubens Pastor",
    capacity: "",
    date: "21/06/2026",
    dateFilter: "21 Jun",
    type: "shows",
    lat: -8.4203,
    lng: -37.0538,
  },
  {
    id: 10,
    title: "N.I.X Machine",
    location: "Polo Multimusical Rubens Pastor",
    capacity: "",
    date: "21/06/2026",
    dateFilter: "21 Jun",
    type: "shows",
    lat: -8.4124,
    lng: -37.0462,
  },
  {
    id: 11,
    title: "Batalha dos Bruxos",
    location: "Polo Multimusical Rubens Pastor",
    capacity: "",
    date: "21/06/2026",
    dateFilter: "21 Jun",
    type: "shows",
    lat: -8.4187,
    lng: -37.0594,
  },
  {
    id: 12,
    title: "Wondera",
    location: "Polo Multimusical Rubens Pastor",
    capacity: "",
    date: "22/06/2026",
    dateFilter: "22 Jun",
    type: "shows",
    lat: -8.4226,
    lng: -37.0505,
  },
  {
    id: 13,
    title: "Mago Rm",
    location: "Polo Multimusical Rubens Pastor",
    capacity: "",
    date: "22/06/2026",
    dateFilter: "22 Jun",
    type: "shows",
    lat: -8.4141,
    lng: -37.0643,
  },
  {
    id: 14,
    title: "Cubana Rasta",
    location: "Polo Multimusical Rubens Pastor",
    capacity: "",
    date: "22/06/2026",
    dateFilter: "22 Jun",
    type: "shows",
    lat: -8.4192,
    lng: -37.0556,
  },
  {
    id: 15,
    title: "Felixdi",
    location: "Polo Multimusical Rubens Pastor",
    capacity: "",
    date: "23/06/2026",
    dateFilter: "23 Jun",
    type: "shows",
    lat: -8.4165,
    lng: -37.0481,
  },
  {
    id: 16,
    title: "DJ Diego Mira",
    location: "Polo Multimusical Rubens Pastor",
    capacity: "",
    date: "23/06/2026",
    dateFilter: "23 Jun",
    type: "shows",
    lat: -8.4239,
    lng: -37.0617,
  },
  {
    id: 17,
    title: "Guira e a eletro Banda Cabaçal",
    location: "Polo Multimusical Rubens Pastor",
    capacity: "",
    date: "23/06/2026",
    dateFilter: "23 Jun",
    type: "shows",
    lat: -8.4128,
    lng: -37.0529,
  },
  {
    id: 18,
    title: "Mc Oh Brabo",
    location: "Polo Multimusical Rubens Pastor",
    capacity: "",
    date: "23/06/2026",
    dateFilter: "23 Jun",
    type: "shows",
    lat: -8.4211,
    lng: -37.0454,
  },
  {
    id: 19,
    title: "Fetus",
    location: "Polo Multimusical Rubens Pastor",
    capacity: "",
    date: "24/06/2026",
    dateFilter: "24 Jun",
    type: "shows",
    lat: -8.4152,
    lng: -37.0587,
  },
  {
    id: 20,
    title: "Zord, The Goat",
    location: "Polo Multimusical Rubens Pastor",
    capacity: "",
    date: "24/06/2026",
    dateFilter: "24 Jun",
    type: "shows",
    lat: -8.4198,
    lng: -37.0518,
  },
  {
    id: 21,
    title: "Song Livre.com",
    location: "Polo Multimusical Rubens Pastor",
    capacity: "",
    date: "24/06/2026",
    dateFilter: "24 Jun",
    type: "shows",
    lat: -8.4242,
    lng: -37.0632,
  },
  {
    id: 22,
    title: "Boreal",
    location: "Polo Multimusical Rubens Pastor",
    capacity: "",
    date: "24/06/2026",
    dateFilter: "24 Jun",
    type: "shows",
    lat: -8.4137,
    lng: -37.0496,
  },
  {
    id: 23,
    title: "Felipe Novo",
    location: "Polo do CGA",
    capacity: "",
    date: "19/06/2026",
    dateFilter: "19 Jun",
    type: "shows",
    lat: -8.4179,
    lng: -37.0574,
  },
  {
    id: 24,
    title: "Paulinha Mel",
    location: "Polo do CGA",
    capacity: "",
    date: "20/06/2026",
    dateFilter: "20 Jun",
    type: "shows",
    lat: -8.4223,
    lng: -37.0468,
  },
  {
    id: 25,
    title: "Edson Augusto e Forró dos Três",
    location: "Polo do CGA",
    capacity: "",
    date: "20/06/2026",
    dateFilter: "20 Jun",
    type: "shows",
    lat: -8.4149,
    lng: -37.0609,
  },
  {
    id: 26,
    title: "Art' Nordestina",
    location: "Polo do CGA",
    capacity: "",
    date: "21/06/2026",
    dateFilter: "21 Jun",
    type: "shows",
    lat: -8.4191,
    lng: -37.0532,
  },
  {
    id: 27,
    title: "Gil Mendes",
    location: "Polo do CGA",
    capacity: "",
    date: "22/06/2026",
    dateFilter: "22 Jun",
    type: "shows",
    lat: -8.4235,
    lng: -37.0483,
  },
  {
    id: 28,
    title: "Forró sem Limites",
    location: "Polo do CGA",
    capacity: "",
    date: "22/06/2026",
    dateFilter: "22 Jun",
    type: "shows",
    lat: -8.4126,
    lng: -37.0621,
  },
  {
    id: 29,
    title: "Elder Brasil",
    location: "Polo do CGA",
    capacity: "",
    date: "23/06/2026",
    dateFilter: "23 Jun",
    type: "shows",
    lat: -8.4207,
    lng: -37.0545,
  },
  {
    id: 30,
    title: "Pedrinho do Forró",
    location: "Polo do CGA",
    capacity: "",
    date: "23/06/2026",
    dateFilter: "23 Jun",
    type: "shows",
    lat: -8.4157,
    lng: -37.0457,
  },
  {
    id: 31,
    title: "Forró Chamego Quente",
    location: "Polo do CGA",
    capacity: "",
    date: "24/06/2026",
    dateFilter: "24 Jun",
    type: "shows",
    lat: -8.4248,
    lng: -37.0597,
  },
  {
    id: 32,
    title: "Ewerton Macedo",
    location: "Polo do CGA",
    capacity: "",
    date: "24/06/2026",
    dateFilter: "24 Jun",
    type: "shows",
    lat: -8.4139,
    lng: -37.0509,
  },
  {
    id: 33,
    title: "Ruana Nascimento",
    location: "Polo do CGA",
    capacity: "",
    date: "27/06/2026",
    dateFilter: "27 Jun",
    type: "shows",
    lat: -8.4183,
    lng: -37.0637,
  },
  {
    id: 34,
    title: "Forró do Povo",
    location: "Polo do CGA",
    capacity: "",
    date: "28/06/2026",
    dateFilter: "28 Jun",
    type: "shows",
    lat: -8.4228,
    lng: -37.0472,
  },
  {
    id: 35,
    title: "Exposição Moxotó - Minha Arte, Minha Vida (Romualdo Freitas)",
    location: "Estação da Cultura",
    capacity: "",
    date: "19-28/06/2026",
    dateFilter: "Todos",
    type: "exposições",
    lat: -8.4144,
    lng: -37.0552,
  },
  {
    id: 36,
    title: "Forró na Feira",
    location: "Arraiá do CECORA",
    capacity: "",
    date: "13/06/2026",
    dateFilter: "13 Jun",
    type: "shows",
    lat: -8.4201,
    lng: -37.0493,
  },
  {
    id: 37,
    title: "Neguinho Arcoverde",
    location: "Arraiá do CECORA",
    capacity: "",
    date: "20/06/2026",
    dateFilter: "20 Jun",
    type: "shows",
    lat: -8.4162,
    lng: -37.0614,
  },
  {
    id: 38,
    title: "Marquinhos Pernambucano",
    location: "Arraiá do CECORA",
    capacity: "",
    date: "27/06/2026",
    dateFilter: "27 Jun",
    type: "shows",
    lat: -8.4241,
    lng: -37.0531,
  },
  {
    id: 39,
    title: "Arrocha Noiz",
    location: "Polo da Cruz",
    capacity: "",
    date: "19/06/2026",
    dateFilter: "19 Jun",
    type: "shows",
    lat: -8.4135,
    lng: -37.0465,
  },
  {
    id: 40,
    title: "Robson Torres",
    location: "Polo da Cruz",
    capacity: "",
    date: "19/06/2026",
    dateFilter: "19 Jun",
    type: "shows",
    lat: -8.4194,
    lng: -37.0581,
  },
  {
    id: 41,
    title: "Gilene Alves",
    location: "Polo da Cruz",
    capacity: "",
    date: "20/06/2026",
    dateFilter: "20 Jun",
    type: "shows",
    lat: -8.4237,
    lng: -37.0519,
  },
  {
    id: 42,
    title: "Raul e Rogério",
    location: "Polo da Cruz",
    capacity: "",
    date: "20/06/2026",
    dateFilter: "20 Jun",
    type: "shows",
    lat: -8.4121,
    lng: -37.0648,
  },
  {
    id: 43,
    title: "Cícero do Acordeon",
    location: "Polo da Cruz",
    capacity: "",
    date: "21/06/2026",
    dateFilter: "21 Jun",
    type: "shows",
    lat: -8.4185,
    lng: -37.0562,
  },
  {
    id: 44,
    title: "Tempero Nordestino",
    location: "Polo da Cruz",
    capacity: "",
    date: "21/06/2026",
    dateFilter: "21 Jun",
    type: "shows",
    lat: -8.4151,
    lng: -37.0487,
  },
  {
    id: 45,
    title: "Giovane do Acordeon",
    location: "Polo da Cruz",
    capacity: "",
    date: "22/06/2026",
    dateFilter: "22 Jun",
    type: "shows",
    lat: -8.4221,
    lng: -37.0628,
  },
  {
    id: 46,
    title: "Rodolfo Melo",
    location: "Polo da Cruz",
    capacity: "",
    date: "22/06/2026",
    dateFilter: "22 Jun",
    type: "shows",
    lat: -8.4138,
    lng: -37.0535,
  },
  {
    id: 47,
    title: "Românticos do Forró",
    location: "Polo da Cruz",
    capacity: "",
    date: "23/06/2026",
    dateFilter: "23 Jun",
    type: "shows",
    lat: -8.4214,
    lng: -37.0459,
  },
  {
    id: 48,
    title: "Tião Gavião",
    location: "Polo da Cruz",
    capacity: "",
    date: "23/06/2026",
    dateFilter: "23 Jun",
    type: "shows",
    lat: -8.4167,
    lng: -37.0592,
  },
  {
    id: 49,
    title: "Zé Coco",
    location: "Polo da Cruz",
    capacity: "",
    date: "24/06/2026",
    dateFilter: "24 Jun",
    type: "shows",
    lat: -8.4246,
    lng: -37.0503,
  },
  {
    id: 50,
    title: "Zezito Santos Alegria do Forró",
    location: "Polo da Cruz",
    capacity: "",
    date: "24/06/2026",
    dateFilter: "24 Jun",
    type: "shows",
    lat: -8.4129,
    lng: -37.0635,
  },
  {
    id: 51,
    title: "Carrim Maraes Aboiador",
    location: "Polo da Poesia Elizeu Pereira",
    capacity: "",
    date: "19/06/2026",
    dateFilter: "19 Jun",
    type: "shows",
    lat: -8.4197,
    lng: -37.0541,
  },
  {
    id: 52,
    title: "Luiz Wilson",
    location: "Polo da Poesia Elizeu Pereira",
    capacity: "",
    date: "19/06/2026",
    dateFilter: "19 Jun",
    type: "shows",
    lat: -8.4143,
    lng: -37.0478,
  },
  {
    id: 53,
    title: "Lídio Vaz",
    location: "Polo da Poesia Elizeu Pereira",
    capacity: "",
    date: "20/06/2026",
    dateFilter: "20 Jun",
    type: "shows",
    lat: -8.4232,
    lng: -37.0607,
  },
  {
    id: 54,
    title: "Leandro Vaz",
    location: "Polo da Poesia Elizeu Pereira",
    capacity: "",
    date: "20/06/2026",
    dateFilter: "20 Jun",
    type: "shows",
    lat: -8.4172,
    lng: -37.0526,
  },
  {
    id: 55,
    title: "Gabi Cysneiros",
    location: "Polo da Poesia Elizeu Pereira",
    capacity: "",
    date: "20/06/2026",
    dateFilter: "20 Jun",
    type: "shows",
    lat: -8.4216,
    lng: -37.0463,
  },
  {
    id: 56,
    title: "Sintonia Pegada Quente",
    location: "Polo da Poesia Elizeu Pereira",
    capacity: "",
    date: "21/06/2026",
    dateFilter: "21 Jun",
    type: "shows",
    lat: -8.4154,
    lng: -37.0584,
  },
  {
    id: 57,
    title: "Diosman Avelino - Do Verso ao Choro",
    location: "Polo da Poesia Elizeu Pereira",
    capacity: "",
    date: "22/06/2026",
    dateFilter: "22 Jun",
    type: "shows",
    lat: -8.4199,
    lng: -37.0515,
  },
  {
    id: 58,
    title: "Mestre Alberone Rabequeiro",
    location: "Polo da Poesia Elizeu Pereira",
    capacity: "",
    date: "22/06/2026",
    dateFilter: "22 Jun",
    type: "shows",
    lat: -8.4243,
    lng: -37.0641,
  },
  {
    id: 59,
    title: "Café em Cena",
    location: "Polo da Poesia Elizeu Pereira",
    capacity: "",
    date: "23/06/2026",
    dateFilter: "23 Jun",
    type: "shows",
    lat: -8.4134,
    lng: -37.0498,
  },
  {
    id: 60,
    title: "MAMA - Arcoverde (En)Canto",
    location: "Polo da Poesia Elizeu Pereira",
    capacity: "",
    date: "23/06/2026",
    dateFilter: "23 Jun",
    type: "shows",
    lat: -8.4181,
    lng: -37.0571,
  },
  {
    id: 61,
    title: "Isabelly Moreira",
    location: "Polo da Poesia Elizeu Pereira",
    capacity: "",
    date: "23/06/2026",
    dateFilter: "23 Jun",
    type: "shows",
    lat: -8.4224,
    lng: -37.0485,
  },
  {
    id: 62,
    title: "Paulinho do Forró",
    location: "Polo da Poesia Elizeu Pereira",
    capacity: "",
    date: "24/06/2026",
    dateFilter: "24 Jun",
    type: "shows",
    lat: -8.4146,
    lng: -37.0612,
  },
  {
    id: 63,
    title: "Manoel Lima Repentista",
    location: "Polo da Poesia Elizeu Pereira",
    capacity: "",
    date: "24/06/2026",
    dateFilter: "24 Jun",
    type: "shows",
    lat: -8.4191,
    lng: -37.0534,
  },
  {
    id: 64,
    title: "Tenório Barros",
    location: "Polo da Poesia Elizeu Pereira",
    capacity: "",
    date: "27/06/2026",
    dateFilter: "27 Jun",
    type: "shows",
    lat: -8.4236,
    lng: -37.0471,
  },
  {
    id: 65,
    title: "Cacau Arcoverde",
    location: "Polo da Poesia Elizeu Pereira",
    capacity: "",
    date: "27/06/2026",
    dateFilter: "27 Jun",
    type: "shows",
    lat: -8.4125,
    lng: -37.0625,
  },
  {
    id: 66,
    title: "Zé Carlos Pajeú",
    location: "Polo da Poesia Elizeu Pereira",
    capacity: "",
    date: "28/06/2026",
    dateFilter: "28 Jun",
    type: "shows",
    lat: -8.4208,
    lng: -37.0549,
  },
  {
    id: 67,
    title: "Anchieta Dali",
    location: "Polo da Poesia Elizeu Pereira",
    capacity: "",
    date: "28/06/2026",
    dateFilter: "28 Jun",
    type: "shows",
    lat: -8.4158,
    lng: -37.0452,
  },
  {
    id: 68,
    title: "Sofia Aboiadora",
    location: "Polo da Poesia Elizeu Pereira",
    capacity: "",
    date: "28/06/2026",
    dateFilter: "28 Jun",
    type: "shows",
    lat: -8.4247,
    lng: -37.0591,
  },
  {
    id: 69,
    title: "Farra dos Poetas",
    location: "Polo da Poesia Elizeu Pereira",
    capacity: "",
    date: "28/06/2026",
    dateFilter: "28 Jun",
    type: "shows",
    lat: -8.4136,
    lng: -37.0506,
  },
  {
    id: 70,
    title: "Reisado Encanto das Caraíbas",
    location: "Polo das Artes Henry Pereira",
    capacity: "",
    date: "19/06/2026",
    dateFilter: "19 Jun",
    type: "shows",
    lat: -8.4182,
    lng: -37.0639,
  },
  {
    id: 71,
    title: "Quadrilha Junina Rainha Sertaneja",
    location: "Polo das Artes Henry Pereira",
    capacity: "",
    date: "19/06/2026",
    dateFilter: "19 Jun",
    type: "shows",
    lat: -8.4229,
    lng: -37.0479,
  },
  {
    id: 72,
    title: "Samba de Coco Quebra Coco Aliança",
    location: "Polo das Artes Henry Pereira",
    capacity: "",
    date: "19/06/2026",
    dateFilter: "19 Jun",
    type: "shows",
    lat: -8.4145,
    lng: -37.0559,
  },
  {
    id: 73,
    title: "Cadilac Tangerina",
    location: "Polo das Artes Henry Pereira",
    capacity: "",
    date: "19/06/2026",
    dateFilter: "19 Jun",
    type: "shows",
    lat: -8.4202,
    lng: -37.0491,
  },
  {
    id: 74,
    title: "Coco Fulô do Barro",
    location: "Polo das Artes Henry Pereira",
    capacity: "",
    date: "20/06/2026",
    dateFilter: "20 Jun",
    type: "shows",
    lat: -8.4161,
    lng: -37.0611,
  },
  {
    id: 75,
    title: "Regente Joaquim",
    location: "Polo das Artes Henry Pereira",
    capacity: "",
    date: "20/06/2026",
    dateFilter: "20 Jun",
    type: "shows",
    lat: -8.4242,
    lng: -37.0536,
  },
  {
    id: 76,
    title: "Caike Souza",
    location: "Polo das Artes Henry Pereira",
    capacity: "",
    date: "20/06/2026",
    dateFilter: "20 Jun",
    type: "shows",
    lat: -8.4133,
    lng: -37.0461,
  },
  {
    id: 77,
    title: "Samba de Coco Trupé de Arcoverde",
    location: "Polo das Artes Henry Pereira",
    capacity: "",
    date: "21/06/2026",
    dateFilter: "21 Jun",
    type: "shows",
    lat: -8.4193,
    lng: -37.0586,
  },
  {
    id: 78,
    title: "Lia Morais",
    location: "Polo das Artes Henry Pereira",
    capacity: "",
    date: "21/06/2026",
    dateFilter: "21 Jun",
    type: "shows",
    lat: -8.4238,
    lng: -37.0514,
  },
  {
    id: 79,
    title: "Vertin Moura",
    location: "Polo das Artes Henry Pereira",
    capacity: "",
    date: "21/06/2026",
    dateFilter: "21 Jun",
    type: "shows",
    lat: -8.4123,
    lng: -37.0645,
  },
  {
    id: 80,
    title: "Coco Pisada Segura",
    location: "Polo das Artes Henry Pereira",
    capacity: "",
    date: "22/06/2026",
    dateFilter: "22 Jun",
    type: "shows",
    lat: -8.4186,
    lng: -37.0569,
  },
  {
    id: 81,
    title: "Motumbaxé",
    location: "Polo das Artes Henry Pereira",
    capacity: "",
    date: "22/06/2026",
    dateFilter: "22 Jun",
    type: "shows",
    lat: -8.4152,
    lng: -37.0482,
  },
  {
    id: 82,
    title: "Oba Aiyê",
    location: "Polo das Artes Henry Pereira",
    capacity: "",
    date: "22/06/2026",
    dateFilter: "22 Jun",
    type: "shows",
    lat: -8.4222,
    lng: -37.0621,
  },
  {
    id: 83,
    title: "Helena Cristina",
    location: "Polo das Artes Henry Pereira",
    capacity: "",
    date: "22/06/2026",
    dateFilter: "22 Jun",
    type: "shows",
    lat: -8.4139,
    lng: -37.0531,
  },
  {
    id: 84,
    title: "Reisado Mirim N. Sra do Rosário",
    location: "Polo das Artes Henry Pereira",
    capacity: "",
    date: "23/06/2026",
    dateFilter: "23 Jun",
    type: "shows",
    lat: -8.4213,
    lng: -37.0456,
  },
  {
    id: 85,
    title: "En'cantos do Coco",
    location: "Polo das Artes Henry Pereira",
    capacity: "",
    date: "23/06/2026",
    dateFilter: "23 Jun",
    type: "shows",
    lat: -8.4168,
    lng: -37.0596,
  },
  {
    id: 86,
    title: "Jú Cavalcanti",
    location: "Polo das Artes Henry Pereira",
    capacity: "",
    date: "23/06/2026",
    dateFilter: "23 Jun",
    type: "shows",
    lat: -8.4244,
    lng: -37.0508,
  },
  {
    id: 87,
    title: "Gabi da Pele Preta",
    location: "Polo das Artes Henry Pereira",
    capacity: "",
    date: "23/06/2026",
    dateFilter: "23 Jun",
    type: "shows",
    lat: -8.4127,
    lng: -37.0632,
  },
  {
    id: 88,
    title: "Afoxé Ya Omi Ogunté",
    location: "Polo das Artes Henry Pereira",
    capacity: "",
    date: "24/06/2026",
    dateFilter: "24 Jun",
    type: "shows",
    lat: -8.4196,
    lng: -37.0546,
  },
  {
    id: 89,
    title: "Coco D'Malandro",
    location: "Polo das Artes Henry Pereira",
    capacity: "",
    date: "24/06/2026",
    dateFilter: "24 Jun",
    type: "shows",
    lat: -8.4142,
    lng: -37.0473,
  },
  {
    id: 90,
    title: "Transcoco",
    location: "Polo das Artes Henry Pereira",
    capacity: "",
    date: "24/06/2026",
    dateFilter: "24 Jun",
    type: "shows",
    lat: -8.4233,
    lng: -37.0604,
  },
  {
    id: 91,
    title: "Driko",
    location: "Polo das Artes Henry Pereira",
    capacity: "",
    date: "24/06/2026",
    dateFilter: "24 Jun",
    type: "shows",
    lat: -8.4173,
    lng: -37.0522,
  },
  {
    id: 92,
    title: "Manacá Samba de Coco Juremado",
    location: "Polo das Artes Henry Pereira",
    capacity: "",
    date: "27/06/2026",
    dateFilter: "27 Jun",
    type: "shows",
    lat: -8.4215,
    lng: -37.0468,
  },
  {
    id: 93,
    title: "Tonino Arcoverde",
    location: "Polo das Artes Henry Pereira",
    capacity: "",
    date: "27/06/2026",
    dateFilter: "27 Jun",
    type: "shows",
    lat: -8.4153,
    lng: -37.0581,
  },
  {
    id: 94,
    title: "Forró Rabecado",
    location: "Polo das Artes Henry Pereira",
    capacity: "",
    date: "27/06/2026",
    dateFilter: "27 Jun",
    type: "shows",
    lat: -8.4198,
    lng: -37.0512,
  },
  {
    id: 95,
    title: "Forró na Caixa",
    location: "Polo das Artes Henry Pereira",
    capacity: "",
    date: "27/06/2026",
    dateFilter: "27 Jun",
    type: "shows",
    lat: -8.4241,
    lng: -37.0643,
  },
  {
    id: 96,
    title: "Samba de Coco Erêmin",
    location: "Polo das Artes Henry Pereira",
    capacity: "",
    date: "28/06/2026",
    dateFilter: "28 Jun",
    type: "shows",
    lat: -8.4131,
    lng: -37.0494,
  },
  {
    id: 97,
    title: "Kelly Rosa",
    location: "Polo das Artes Henry Pereira",
    capacity: "",
    date: "28/06/2026",
    dateFilter: "28 Jun",
    type: "shows",
    lat: -8.4184,
    lng: -37.0573,
  },
  {
    id: 98,
    title: "Larissa Gois",
    location: "Polo das Artes Henry Pereira",
    capacity: "",
    date: "28/06/2026",
    dateFilter: "28 Jun",
    type: "shows",
    lat: -8.4225,
    lng: -37.0482,
  },
  {
    id: 99,
    title: "Jaime Mendes",
    location: "Polo das Artes Henry Pereira",
    capacity: "",
    date: "28/06/2026",
    dateFilter: "28 Jun",
    type: "shows",
    lat: -8.4148,
    lng: -37.0614,
  },
  {
    id: 100,
    title: "Ademir e Banda",
    location: "Polo Pé de Serra João Silva",
    capacity: "",
    date: "19/06/2026",
    dateFilter: "19 Jun",
    type: "shows",
    lat: -8.4192,
    lng: -37.0531,
  },
  {
    id: 101,
    title: "Silvia Regina",
    location: "Polo Pé de Serra João Silva",
    capacity: "",
    date: "19/06/2026",
    dateFilter: "19 Jun",
    type: "shows",
    lat: -8.4234,
    lng: -37.0475,
  },
  {
    id: 102,
    title: "Forró Maktub",
    location: "Polo Pé de Serra João Silva",
    capacity: "",
    date: "20/06/2026",
    dateFilter: "20 Jun",
    type: "shows",
    lat: -8.4124,
    lng: -37.0628,
  },
  {
    id: 103,
    title: "Forró de Pai pra Filho",
    location: "Polo Pé de Serra João Silva",
    capacity: "",
    date: "20/06/2026",
    dateFilter: "20 Jun",
    type: "shows",
    lat: -8.4209,
    lng: -37.0547,
  },
  {
    id: 104,
    title: "Sergio Coringa e Cilene a Flor do Sertão",
    location: "Polo Pé de Serra João Silva",
    capacity: "",
    date: "21/06/2026",
    dateFilter: "21 Jun",
    type: "shows",
    lat: -8.4159,
    lng: -37.0456,
  },
  {
    id: 105,
    title: "Cição",
    location: "Polo Pé de Serra João Silva",
    capacity: "",
    date: "21/06/2026",
    dateFilter: "21 Jun",
    type: "shows",
    lat: -8.4249,
    lng: -37.0594,
  },
  {
    id: 106,
    title: "Zé do Peba e Trio Catingueira",
    location: "Polo Pé de Serra João Silva",
    capacity: "",
    date: "22/06/2026",
    dateFilter: "22 Jun",
    type: "shows",
    lat: -8.4137,
    lng: -37.0504,
  },
  {
    id: 107,
    title: "Pau no Xote",
    location: "Polo Pé de Serra João Silva",
    capacity: "",
    date: "22/06/2026",
    dateFilter: "22 Jun",
    type: "shows",
    lat: -8.4181,
    lng: -37.0632,
  },
  {
    id: 108,
    title: "James Vaqueiro",
    location: "Polo Pé de Serra João Silva",
    capacity: "",
    date: "23/06/2026",
    dateFilter: "23 Jun",
    type: "shows",
    lat: -8.4226,
    lng: -37.0478,
  },
  {
    id: 109,
    title: "Lorenção",
    location: "Polo Pé de Serra João Silva",
    capacity: "",
    date: "23/06/2026",
    dateFilter: "23 Jun",
    type: "shows",
    lat: -8.4144,
    lng: -37.0556,
  },
  {
    id: 110,
    title: "Boka Diniz",
    location: "Polo Pé de Serra João Silva",
    capacity: "",
    date: "23/06/2026",
    dateFilter: "23 Jun",
    type: "shows",
    lat: -8.4203,
    lng: -37.0494,
  },
  {
    id: 111,
    title: "Tiago e Dineide Araújo",
    location: "Polo Pé de Serra João Silva",
    capacity: "",
    date: "24/06/2026",
    dateFilter: "24 Jun",
    type: "shows",
    lat: -8.4164,
    lng: -37.0617,
  },
  {
    id: 112,
    title: "Vaqueirões do Forró",
    location: "Polo Pé de Serra João Silva",
    capacity: "",
    date: "24/06/2026",
    dateFilter: "24 Jun",
    type: "shows",
    lat: -8.4243,
    lng: -37.0534,
  },
  {
    id: 113,
    title: "Ricardo Lima",
    location: "Polo Pé de Serra João Silva",
    capacity: "",
    date: "27/06/2026",
    dateFilter: "27 Jun",
    type: "shows",
    lat: -8.4132,
    lng: -37.0468,
  },
  {
    id: 114,
    title: "Daci Pires e Forró Baluarte",
    location: "Polo Pé de Serra João Silva",
    capacity: "",
    date: "27/06/2026",
    dateFilter: "27 Jun",
    type: "shows",
    lat: -8.4195,
    lng: -37.0583,
  },
  {
    id: 115,
    title: "Zezinho do Acordeon",
    location: "Polo Pé de Serra João Silva",
    capacity: "",
    date: "28/06/2026",
    dateFilter: "28 Jun",
    type: "shows",
    lat: -8.4239,
    lng: -37.0516,
  },
  {
    id: 116,
    title: "Forró Júnior Saygon",
    location: "Polo Pé de Serra João Silva",
    capacity: "",
    date: "28/06/2026",
    dateFilter: "28 Jun",
    type: "shows",
    lat: -8.4121,
    lng: -37.0649,
  },
  {
    id: 117,
    title: "Coco das Irmãs Lopes",
    location: "Polo Principal (São João de Arcoverde)",
    capacity: "",
    date: "13/06/2026",
    dateFilter: "13 Jun",
    type: "shows",
    lat: -8.4187,
    lng: -37.0564,
  },
  {
    id: 118,
    title: "Flávio José",
    location: "Polo Principal (São João de Arcoverde)",
    capacity: "",
    date: "13/06/2026",
    dateFilter: "13 Jun",
    type: "shows",
    lat: -8.4192,
    lng: -37.0521,
    image: "images/singers/flavio-jose.jpg",
  },
  {
    id: 119,
    title: "Alceu Valença",
    location: "Polo Principal (São João de Arcoverde)",
    capacity: "",
    date: "13/06/2026",
    dateFilter: "13 Jun",
    type: "shows",
    lat: -8.4175,
    lng: -37.0558,
    image: "images/singers/alceu-valenca.jpg",
  },
  {
    id: 120,
    title: "PV Calado",
    location: "Polo Principal (São João de Arcoverde)",
    capacity: "",
    date: "14/06/2026",
    dateFilter: "14 Jun",
    type: "shows",
    lat: -8.4153,
    lng: -37.0489,
  },
  {
    id: 121,
    title: "Junior e Jorge",
    location: "Polo Principal (São João de Arcoverde)",
    capacity: "",
    date: "14/06/2026",
    dateFilter: "14 Jun",
    type: "shows",
    lat: -8.4224,
    lng: -37.0623,
  },
  {
    id: 122,
    title: "Lipe Lucena",
    location: "Polo Principal (São João de Arcoverde)",
    capacity: "",
    date: "14/06/2026",
    dateFilter: "14 Jun",
    type: "shows",
    lat: -8.4136,
    lng: -37.0537,
  },
  {
    id: 123,
    title: "Festival de Quadrilhas",
    location: "Polo Principal (São João de Arcoverde)",
    capacity: "",
    date: "15/06/2026",
    dateFilter: "15 Jun",
    type: "shows",
    lat: -8.4215,
    lng: -37.0458,
  },
  {
    id: 124,
    title: "Jució",
    location: "Polo Principal (São João de Arcoverde)",
    capacity: "",
    date: "16/06/2026",
    dateFilter: "16 Jun",
    type: "shows",
    lat: -8.4205,
    lng: -37.0532,
    image: "images/singers/jucie.jpg",
    bgPosition: "center 15%",
  },
  {
    id: 125,
    title: "Zé Vaqueiro",
    location: "Polo Principal (São João de Arcoverde)",
    capacity: "",
    date: "16/06/2026",
    dateFilter: "16 Jun",
    type: "shows",
    lat: -8.4168,
    lng: -37.0565,
    image: "images/singers/ze-vaqueiro.jpg",
    bgPosition: "center 15%",
  },
  {
    id: 126,
    title: "Nattan",
    location: "Polo Principal (São João de Arcoverde)",
    capacity: "",
    date: "16/06/2026",
    dateFilter: "16 Jun",
    type: "shows",
    lat: -8.4181,
    lng: -37.0512,
    image: "images/singers/nattan.jpg",
    bgPosition: "center 15%",
  },
  {
    id: 127,
    title: "Fernandinha",
    location: "Polo Principal (São João de Arcoverde)",
    capacity: "",
    date: "17/06/2026",
    dateFilter: "17 Jun",
    type: "shows",
    lat: -8.4212,
    lng: -37.0549,
    bgPosition: "center 15%",
  },
  {
    id: 128,
    title: "Eric Land",
    location: "Polo Principal (São João de Arcoverde)",
    capacity: "",
    date: "17/06/2026",
    dateFilter: "17 Jun",
    type: "shows",
    lat: -8.4155,
    lng: -37.0538,
    bgPosition: "center 15%",
  },
  {
    id: 129,
    title: "Vitor Fernandes",
    location: "Polo Principal (São João de Arcoverde)",
    capacity: "",
    date: "17/06/2026",
    dateFilter: "17 Jun",
    type: "shows",
    lat: -8.4169,
    lng: -37.0594,
  },
  {
    id: 130,
    title: "Maciel Kuré",
    location: "Polo Principal (São João de Arcoverde)",
    capacity: "",
    date: "18/06/2026",
    dateFilter: "18 Jun",
    type: "shows",
    lat: -8.4248,
    lng: -37.0505,
  },
  {
    id: 131,
    title: "Iguinho e Lulinha",
    location: "Polo Principal (São João de Arcoverde)",
    capacity: "",
    date: "18/06/2026",
    dateFilter: "18 Jun",
    type: "shows",
    lat: -8.4198,
    lng: -37.0572,
    image: "images/singers/iguinho-e-lulinha.jpg",
  },
  {
    id: 132,
    title: "Wesley Safadão",
    location: "Polo Principal (São João de Arcoverde)",
    capacity: "",
    date: "18/06/2026",
    dateFilter: "18 Jun",
    type: "shows",
    lat: -8.4172,
    lng: -37.0525,
    image: "images/singers/wesley-safadao.jpg",
    bgPosition: "center",
  },
  {
    id: 133,
    title: "Dani Aguiar",
    location: "Polo Principal (São João de Arcoverde)",
    capacity: "",
    date: "19/06/2026",
    dateFilter: "19 Jun",
    type: "shows",
    lat: -8.4131,
    lng: -37.0637,
  },
  {
    id: 134,
    title: "Talita Mel",
    location: "Polo Principal (São João de Arcoverde)",
    capacity: "",
    date: "19/06/2026",
    dateFilter: "19 Jun",
    type: "shows",
    lat: -8.4199,
    lng: -37.0543,
  },
  {
    id: 135,
    title: "Priscila Senna",
    location: "Polo Principal (São João de Arcoverde)",
    capacity: "",
    date: "19/06/2026",
    dateFilter: "19 Jun",
    type: "shows",
    lat: -8.4145,
    lng: -37.0471,
  },
  {
    id: 136,
    title: "Mayana Neiva",
    location: "Polo Principal (São João de Arcoverde)",
    capacity: "",
    date: "20/06/2026",
    dateFilter: "20 Jun",
    type: "shows",
    lat: -8.4234,
    lng: -37.0602,
  },
  {
    id: 137,
    title: "Edy & Nathan",
    location: "Polo Principal (São João de Arcoverde)",
    capacity: "",
    date: "20/06/2026",
    dateFilter: "20 Jun",
    type: "shows",
    lat: -8.4174,
    lng: -37.0524,
  },
  {
    id: 138,
    title: "Fabinho Testado",
    location: "Polo Principal (São João de Arcoverde)",
    capacity: "",
    date: "20/06/2026",
    dateFilter: "20 Jun",
    type: "shows",
    lat: -8.4218,
    lng: -37.0461,
  },
  {
    id: 139,
    title: "Ciro Santos",
    location: "Polo Principal (São João de Arcoverde)",
    capacity: "",
    date: "21/06/2026",
    dateFilter: "21 Jun",
    type: "shows",
    lat: -8.4156,
    lng: -37.0582,
  },
  {
    id: 140,
    title: "Assisão",
    location: "Polo Principal (São João de Arcoverde)",
    capacity: "",
    date: "21/06/2026",
    dateFilter: "21 Jun",
    type: "shows",
    lat: -8.4201,
    lng: -37.0513,
  },
  {
    id: 141,
    title: "Super Oara",
    location: "Polo Principal (São João de Arcoverde)",
    capacity: "",
    date: "21/06/2026",
    dateFilter: "21 Jun",
    type: "shows",
    lat: -8.4245,
    lng: -37.0642,
  },
  {
    id: 142,
    title: "Capital do Sol",
    location: "Polo Principal (São João de Arcoverde)",
    capacity: "",
    date: "21/06/2026",
    dateFilter: "21 Jun",
    type: "shows",
    lat: -8.4136,
    lng: -37.0496,
  },
  {
    id: 143,
    title: "Felipe Amorim",
    location: "Polo Principal (São João de Arcoverde)",
    capacity: "",
    date: "21/06/2026",
    dateFilter: "21 Jun",
    type: "shows",
    lat: -8.4183,
    lng: -37.0571,
  },
  {
    id: 144,
    title: "Coco Fulô do Barro",
    location: "Polo Principal (São João de Arcoverde)",
    capacity: "",
    date: "22/06/2026",
    dateFilter: "22 Jun",
    type: "shows",
    lat: -8.4227,
    lng: -37.0484,
  },
  {
    id: 145,
    title: "Geraldinho Lins",
    location: "Polo Principal (São João de Arcoverde)",
    capacity: "",
    date: "22/06/2026",
    dateFilter: "22 Jun",
    type: "shows",
    lat: -8.4148,
    lng: -37.0614,
  },
  {
    id: 146,
    title: "Garota Safada",
    location: "Polo Principal (São João de Arcoverde)",
    capacity: "",
    date: "22/06/2026",
    dateFilter: "22 Jun",
    type: "shows",
    lat: -8.4194,
    lng: -37.0536,
  },
  {
    id: 147,
    title: "Coco Raízes de Arcoverde",
    location: "Polo Principal (São João de Arcoverde)",
    capacity: "",
    date: "23/06/2026",
    dateFilter: "23 Jun",
    type: "shows",
    lat: -8.4239,
    lng: -37.0474,
  },
  {
    id: 148,
    title: "George Silva",
    location: "Polo Principal (São João de Arcoverde)",
    capacity: "",
    date: "23/06/2026",
    dateFilter: "23 Jun",
    type: "shows",
    lat: -8.4128,
    lng: -37.0628,
  },
  {
    id: 149,
    title: "Jorge de Altinho",
    location: "Polo Principal (São João de Arcoverde)",
    capacity: "",
    date: "23/06/2026",
    dateFilter: "23 Jun",
    type: "shows",
    lat: -8.4209,
    lng: -37.0541,
  },
  {
    id: 150,
    title: "Cordel do Fogo Encantado",
    location: "Polo Principal (São João de Arcoverde)",
    capacity: "",
    date: "23/06/2026",
    dateFilter: "23 Jun",
    type: "shows",
    lat: -8.4161,
    lng: -37.0454,
  },
  {
    id: 151,
    title: "João Vaqueiro",
    location: "Polo Principal (São João de Arcoverde)",
    capacity: "",
    date: "24/06/2026",
    dateFilter: "24 Jun",
    type: "shows",
    lat: -8.4246,
    lng: -37.0592,
  },
  {
    id: 152,
    title: "Magníficos",
    location: "Polo Principal (São João de Arcoverde)",
    capacity: "",
    date: "24/06/2026",
    dateFilter: "24 Jun",
    type: "shows",
    lat: -8.4137,
    lng: -37.0503,
  },
  {
    id: 153,
    title: "Xand Avião",
    location: "Polo Principal (São João de Arcoverde)",
    capacity: "",
    date: "24/06/2026",
    dateFilter: "24 Jun",
    type: "shows",
    lat: -8.4184,
    lng: -37.0634,
  },
  {
    id: 154,
    title: "Will",
    location: "Polo Principal (São João de Arcoverde)",
    capacity: "",
    date: "25/06/2026",
    dateFilter: "25 Jun",
    type: "shows",
    lat: -8.4221,
    lng: -37.0471,
  },
  {
    id: 155,
    title: "Nágilla Ferreira",
    location: "Polo Principal (São João de Arcoverde)",
    capacity: "",
    date: "25/06/2026",
    dateFilter: "25 Jun",
    type: "shows",
    lat: -8.4142,
    lng: -37.0558,
  },
  {
    id: 156,
    title: "João Gomes",
    location: "Polo Principal (São João de Arcoverde)",
    capacity: "",
    date: "25/06/2026",
    dateFilter: "25 Jun",
    type: "shows",
    lat: -8.4201,
    lng: -37.0551,
    image: "images/singers/joao-gomes.webp",
    bgPosition: "center 15%",
  },
  {
    id: 157,
    title: "Ycaro Andrade",
    location: "Polo Principal (São João de Arcoverde)",
    capacity: "",
    date: "26/06/2026",
    dateFilter: "26 Jun",
    type: "shows",
    lat: -8.4197,
    lng: -37.0493,
  },
  {
    id: 158,
    title: "Harry Estigado",
    location: "Polo Principal (São João de Arcoverde)",
    capacity: "",
    date: "26/06/2026",
    dateFilter: "26 Jun",
    type: "shows",
    lat: -8.4164,
    lng: -37.0612,
  },
  {
    id: 159,
    title: "Nathanzinho Lima",
    location: "Polo Principal (São João de Arcoverde)",
    capacity: "",
    date: "26/06/2026",
    dateFilter: "26 Jun",
    type: "shows",
    lat: -8.4243,
    lng: -37.0531,
  },
  {
    id: 160,
    title: "Flávio Leandro",
    location: "Polo Principal (São João de Arcoverde)",
    capacity: "",
    date: "27/06/2026",
    dateFilter: "27 Jun",
    type: "shows",
    lat: -8.4133,
    lng: -37.0464,
  },
  {
    id: 161,
    title: "Noda de Caju",
    location: "Polo Principal (São João de Arcoverde)",
    capacity: "",
    date: "27/06/2026",
    dateFilter: "27 Jun",
    type: "shows",
    lat: -8.4192,
    lng: -37.0583,
  },
  {
    id: 162,
    title: "Limão com Mel",
    location: "Polo Principal (São João de Arcoverde)",
    capacity: "",
    date: "27/06/2026",
    dateFilter: "27 Jun",
    type: "shows",
    lat: -8.4237,
    lng: -37.0518,
  },
  {
    id: 163,
    title: "Carlos e Fábio",
    location: "Polo Principal (São João de Arcoverde)",
    capacity: "",
    date: "28/06/2026",
    dateFilter: "28 Jun",
    type: "shows",
    lat: -8.4121,
    lng: -37.0645,
  },
  {
    id: 164,
    title: "Forrozão Chacal",
    location: "Polo Principal (São João de Arcoverde)",
    capacity: "",
    date: "28/06/2026",
    dateFilter: "28 Jun",
    type: "shows",
    lat: -8.4185,
    lng: -37.0561,
  },
  {
    id: 165,
    title: "Matheus & Kauan",
    location: "Polo Principal (São João de Arcoverde)",
    capacity: "",
    date: "28/06/2026",
    dateFilter: "28 Jun",
    type: "shows",
    lat: -8.4151,
    lng: -37.0487,
  },
  {
    id: 166,
    title: "Hotel Carajás",
    location: "R. Cel. Alencar, 90 — Centro",
    capacity: "Duplo, Triplo",
    date: "",
    dateFilter: "Todos",
    type: "hoteis",
    lat: -8.4178,
    lng: -37.0554,
  },
  {
    id: 167,
    title: "Arcoverde Palace Hotel",
    location: "Av. Cel. José Rufino, 447 — Centro",
    capacity: "Single, Duplo, Suite",
    date: "",
    dateFilter: "Todos",
    type: "hoteis",
    lat: -8.4191,
    lng: -37.0539,
  },
  {
    id: 168,
    title: "Pousada São João",
    location: "R. Aprígio Duarte, 230 — Centro",
    capacity: "Duplo, Familiar",
    date: "",
    dateFilter: "Todos",
    type: "hoteis",
    lat: -8.4165,
    lng: -37.0572,
  },
  {
    id: 169,
    title: "Hotel Sertão Vivo",
    location: "Av. Presidente Vargas, 310 — Centro",
    capacity: "Single, Duplo",
    date: "",
    dateFilter: "Todos",
    type: "hoteis",
    lat: -8.4203,
    lng: -37.0511,
  },
  {
    id: 170,
    title: "Pousada Flor do Sertão",
    location: "R. Santos Dumont, 18 — Bairro Novo",
    capacity: "Duplo, Triplo",
    date: "",
    dateFilter: "Todos",
    type: "hoteis",
    lat: -8.4217,
    lng: -37.0528,
  },
  {
    id: 171,
    title: "Serra do Ororubá",
    location: "PE-165, Km 12 — Zona Rural",
    capacity: "",
    date: "",
    dateFilter: "Todos",
    type: "turisticos",
    lat: -8.3940,
    lng: -37.0650,
  },
  {
    id: 172,
    title: "Parque Ecológico Riacho do Navio",
    location: "Zona Rural de Arcoverde",
    capacity: "",
    date: "",
    dateFilter: "Todos",
    type: "turisticos",
    lat: -8.4300,
    lng: -37.0800,
  },
  {
    id: 173,
    title: "Museu do Cangaço",
    location: "R. Coronel Alencar — Centro",
    capacity: "",
    date: "",
    dateFilter: "Todos",
    type: "turisticos",
    lat: -8.4183,
    lng: -37.0560,
  },
  {
    id: 174,
    title: "Igreja Matriz de Arcoverde",
    location: "Praça Cel. José Rufino — Centro",
    capacity: "",
    date: "",
    dateFilter: "Todos",
    type: "turisticos",
    lat: -8.4175,
    lng: -37.0548,
  },
  {
    id: 175,
    title: "Açude Eng. Armando Ribeiro",
    location: "Estrada do Açude — Zona Norte",
    capacity: "",
    date: "",
    dateFilter: "Todos",
    type: "turisticos",
    lat: -8.4050,
    lng: -37.0420,
  },
  {
    id: 175,
    title: "Polo Multicultural",
    location: "Apos a estacao da cultura",
    capacity: "",
    date: "",
    dateFilter: "Todos",
    type: "polo",
    lat: -8.4050,
    lng: -37.0420,
  },
];

const CAROUSEL_SLIDES = [
  {
    id: 119,
    title: "Alceu Valença",
    sub: "13 Jun  •  Polo Principal",
    color: "#ffc38e",
    image: "images/singers/alceu-valenca.jpg",
    textColor: "white",
  },
  {
    id: 125,
    title: "Zé Vaqueiro",
    sub: "16 Jun  •  Polo Principal",
    color: "#f5b070",
    image: "images/singers/ze-vaqueiro.jpg",
    bgPosition: "center 15%",
    textColor: "white",
  },
  {
    id: 132,
    title: "Wesley Safadão",
    sub: "18 Jun  •  Polo Principal",
    color: "#f0a060",
    image: "images/singers/wesley-safadao.jpg",
    bgPosition: "center top",
  },
  {
    id: 156,
    title: "João Gomes",
    sub: "25 Jun  •  Polo Principal",
    color: "#e89050",
    image: "images/singers/joao-gomes.webp",
    bgPosition: "center 15%",
    textColor: "white",
  },
];

const TRANSPORTE = [
  {
    id: 201,
    title: "Carlos Silva",
    vehicle: "carro",
    route: "Arcoverde → Pesqueira",
    city: "Pesqueira",
    price: "R$ 80",
    contact: "87991110001",
  },
  {
    id: 202,
    title: "Ana Motorista",
    vehicle: "carro",
    route: "Arcoverde → Caruaru",
    city: "Caruaru",
    price: "R$ 150",
    contact: "87991110002",
  },
  {
    id: 203,
    title: "João Van",
    vehicle: "van",
    route: "Arcoverde → Recife",
    city: "Recife",
    price: "R$ 60/pessoa",
    contact: "81991110003",
  },
  {
    id: 204,
    title: "Pedro Táxi",
    vehicle: "carro",
    route: "Arcoverde e região",
    city: "Arcoverde",
    price: "A combinar",
    contact: "87991110004",
  },
  {
    id: 205,
    title: "Moto Fácil",
    vehicle: "moto",
    route: "Arcoverde (cidade)",
    city: "Arcoverde",
    price: "A combinar",
    contact: "87991110005",
  },
  {
    id: 206,
    title: "Trans Garanhuns",
    vehicle: "van",
    route: "Arcoverde → Garanhuns",
    city: "Garanhuns",
    price: "R$ 40/pessoa",
    contact: "87991110006",
  },
  {
    id: 207,
    title: "Renata Motorista",
    vehicle: "carro",
    route: "Arcoverde → Sertânia",
    city: "Sertânia",
    price: "R$ 70",
    contact: "87991110007",
  },
  {
    id: 208,
    title: "Forro Táxi",
    vehicle: "carro",
    route: "Arcoverde → Buíque",
    city: "Buíque",
    price: "R$ 90",
    contact: "87991110008",
  },
];

const TRANSPORT_CITIES = ["Todas", ...new Set(TRANSPORTE.map((t) => t.city))];

const MAP_CONFIG = {
  center: { lat: -8.4186, lng: -37.0544 },
  zoom: 15,
};

const DATE_FILTERS = [
  "Todos",
  ...new Set(ITEMS.map((i) => i.dateFilter).filter((f) => f !== "Todos")),
];
